"""Application distribution contracts shared by CLI and Desktop callers."""

from .check import ApplicationCheckResult, check_application
from .credentials import (
    CREDENTIAL_ACCOUNT,
    CREDENTIAL_SERVICE,
    CredentialStoreError,
    SystemCredentialStore,
)
from .events import (
    DistributionEvent,
    ErrorCode,
    ErrorEvent,
    EventSink,
    ExitCode,
    JsonLineEventWriter,
    ProgressEvent,
    ResultEvent,
    exit_code_for,
)
from .ports import (
    AccessToken,
    CredentialStore,
    DeviceAuthorization,
    HubAuthenticationError,
    HubClient,
    HubError,
    HubIdentity,
    HubInvalidResponse,
    HubNetworkError,
    OAuthClient,
    OAuthAuthorizationDenied,
    OAuthAuthorizationExpired,
    OAuthAuthorizationPending,
    OAuthFlowError,
    OAuthInvalidResponse,
    OAuthNetworkError,
    OAuthRequest,
    OAuthSlowDown,
)
from .login import (
    DEFAULT_OAUTH_REQUEST,
    OAUTH_CLIENT_ID,
    OAUTH_SCOPES,
    LoginError,
    LoginResult,
    LoginStatus,
    login,
    login_status,
    logout,
)
from .source_files import (
    ApplicationSourceError,
    collect_application_source_files,
)

__all__ = [
    "ApplicationCheckResult",
    "ApplicationSourceError",
    "DistributionEvent",
    "AccessToken",
    "CredentialStore",
    "CredentialStoreError",
    "CREDENTIAL_ACCOUNT",
    "CREDENTIAL_SERVICE",
    "DEFAULT_OAUTH_REQUEST",
    "DeviceAuthorization",
    "ErrorCode",
    "ErrorEvent",
    "EventSink",
    "ExitCode",
    "HubClient",
    "HubAuthenticationError",
    "HubError",
    "HubIdentity",
    "HubInvalidResponse",
    "HubNetworkError",
    "JsonLineEventWriter",
    "OAuthClient",
    "OAuthAuthorizationDenied",
    "OAuthAuthorizationExpired",
    "OAuthAuthorizationPending",
    "OAuthFlowError",
    "OAuthInvalidResponse",
    "OAuthNetworkError",
    "OAuthRequest",
    "OAuthSlowDown",
    "OAUTH_CLIENT_ID",
    "OAUTH_SCOPES",
    "ProgressEvent",
    "ResultEvent",
    "SystemCredentialStore",
    "LoginError",
    "LoginResult",
    "LoginStatus",
    "check_application",
    "collect_application_source_files",
    "exit_code_for",
    "login",
    "login_status",
    "logout",
]
